name: 'Terraform'

on:
  push:
    branches: [ "feat/fsi_mgmt" ]
  pull_request:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Terraform Init
      env:
        ARM_SUBSCRIPTION_ID: "ea0a0669-7cd7-4792-aadb-8f128ca2dfef"
        ARM_BACKEND_CONTAINER: "tfstate" 
        ARM_BACKEND_STORAGE_ACCOUNT: "sterranwmgmtsa"
        ARM_BACKEND_STORAGE_ACCOUNT_RG: "rg-err-anw-mgmt-mgmt"
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        #ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_ID }}
      run: |
            container_exists=$(az storage container exists --account-name $ARM_BACKEND_STORAGE_ACCOUNT --subscription $ARM_SUBSCRIPTION_ID --name $ARM_BACKEND_CONTAINER --query exists)   
            container_exists="${container_exists%\"}"
            container_exists="${container_exists#\"}"
            if [ "$container_exists" == "false" ]; then
              az storage container create --subscription "$ARM_SUBSCRIPTION_ID" --name "$ARM_BACKEND_CONTAINER" --public-access off
            fi
            terraform init \
              -backend-config="storage_account_name=$ARM_BACKEND_STORAGE_ACCOUNT" \
              -backend-config="container_name=$ARM_BACKEND_CONTAINER" \
              -backend-config="key=mgmt/core.tfstate" \
              -backend-config="resource_group_name=$ARM_BACKEND_STORAGE_ACCOUNT_RG" \
              -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID" \
              -reconfigure

    - name: Terraform Format
      run: |
          terraform fmt -check
    
    - name: Terraform Plan
      run: |
          terraform plan -var-file management_core.tfvars -input=false
    
    - name: Terraform Apply
      run: |
          terraform apply -var-file management_core.tfvars -auto-approve -input=false
