name: 'Terraform'

on:
  push:
    branches: [ "dev" ]
  pull_request:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: plan

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
    
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Init
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_BACKEND_CONTAINER: "tfstate" 
        ARM_BACKEND_STORAGE_ACCOUNT: "sterranwmgmtsa"
        ARM_BACKEND_STORAGE_ACCOUNT_RG: "rg-err-anw-mgmt-mgmt"
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
          container_exists=$(az storage container exists --account-name $ARM_BACKEND_STORAGE_ACCOUNT --subscription $ARM_SUBSCRIPTION_ID --name $ARM_BACKEND_CONTAINER --query exists)   
          container_exists="${container_exists%\"}"
          container_exists="${container_exists#\"}"
          if [ "$container_exists" == "false" ]; then
            az storage container create --subscription "$ARM_SUBSCRIPTION_ID" --name "$ARM_BACKEND_CONTAINER" --public-access off
          fi
          terraform init \
            -backend-config="storage_account_name=$ARM_BACKEND_STORAGE_ACCOUNT" \
            -backend-config="container_name=$ARM_BACKEND_CONTAINER" \
            -backend-config="key=mgmt/core.tfstate" \
            -backend-config="resource_group_name=$ARM_BACKEND_STORAGE_ACCOUNT_RG" \
            -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID" \
            -reconfigure
    
    - name: Terraform Plan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
          terraform plan -out tfplan.out -var-file management_core.tfvars -input=false
    - uses: actions/upload-artifact@v4
      with:
        name: tf-plan
        path: tfplan.out
  Apply:
    needs: terraform
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: apply
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: tf-plan
        path: /tmp
    - name: Terraform Apply
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
          terraform apply /tmp/tfplan.out
